### ISSUE TITLE
matchertree failed to decode some patterns.

### ISSUE THREAD

**Issue by DataCorrupted** [SecurityLab-UCD/IRFuzzer#43]
On X86 and AMDGCN, `ThePattern.Complexity = (int64_t)PatternObject["complexity"];` still fails. 

@oakrc  I am rolling back to setting complexity to 0 for now.

**Comment by oakrc** [comment]
Does that happen with the latest pattern lookup commit? It shouldn't happen with x86 at least.

**Comment by DataCorrupted** [comment]
Ah thanks. My build script is set to lazy init in the last patch and thus didn't receive your commit yesterday.
